<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="camera_tests.TestCamera-20220429234908" tests="7" file="camera_tests.py" time="0.054" timestamp="2022-04-29T23:49:10" failures="0" errors="7" skipped="0">
	<testcase classname="camera_tests.TestCamera" name="test_camera" time="0.044" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_epoch_end" time="0.002" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_get_suggestion" time="0.002" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_predict_image" time="0.002" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_translation" time="0.002" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_validation_epoch_end" time="0.002" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_validation_step" time="0.002" timestamp="2022-04-29T23:49:10">
		<error type="NameError" message="name 'ResNet152' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 589, in run
    self._callSetUp()
  File "/usr/lib/python3.9/unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 9, in setUp
    self.model = to_device(ResNet152(), self.device)
NameError: name 'ResNet152' is not defined
]]></error>
	</testcase>
</testsuite>
