<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="camera_tests.TestCamera-20220429234339" tests="7" file="camera_tests.py" time="11.801" timestamp="2022-04-29T23:43:53" failures="0" errors="3" skipped="0">
	<testcase classname="camera_tests.TestCamera" name="test_camera" time="3.542" timestamp="2022-04-29T23:43:45"/>
	<testcase classname="camera_tests.TestCamera" name="test_get_suggestion" time="1.491" timestamp="2022-04-29T23:43:48"/>
	<testcase classname="camera_tests.TestCamera" name="test_predict_image" time="1.319" timestamp="2022-04-29T23:43:49"/>
	<testcase classname="camera_tests.TestCamera" name="test_translation" time="1.414" timestamp="2022-04-29T23:43:51"/>
	<testcase classname="camera_tests.TestCamera" name="test_epoch_end" time="1.378" timestamp="2022-04-29T23:43:46">
		<error type="NameError" message="name 'validation_epoch_end' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 41, in test_epoch_end
    hit = validation_epoch_end()
NameError: name 'validation_epoch_end' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_validation_epoch_end" time="1.325" timestamp="2022-04-29T23:43:52">
		<error type="NameError" message="name 'validation_epoch_end' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 33, in test_validation_epoch_end
    hit =validation_epoch_end()
NameError: name 'validation_epoch_end' is not defined
]]></error>
	</testcase>
	<testcase classname="camera_tests.TestCamera" name="test_validation_step" time="1.332" timestamp="2022-04-29T23:43:53">
		<error type="NameError" message="name 'validation_step' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/luka/Desktop/Assignment_6/src/unittest/python/camera_tests.py", line 23, in test_validation_step
    hit =validation_step()
NameError: name 'validation_step' is not defined
]]></error>
	</testcase>
</testsuite>
